### ISSUE TITLE
DateUtilTest fails on machine with German locale

### ISSUE THREAD

**Issue by cypressious** [alisonthemonster/GratitudeJournal#111]
When I run `DateUtilTest` on my machine with the locale set to German, I get the following failures:

```
junit.framework.ComparisonFailure: 
Expected :March
Actual   :März
<Click to see difference>


	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at junit.framework.TestCase.assertEquals(TestCase.java:269)
	at journal.gratitude.com.gratitudejournal.ui.util.DateUtilTest.getMonthStringFromDateObject(DateUtilTest.kt:68)
```

```
junit.framework.ComparisonFailure: 
Expected :November 11, 2011
Actual   :11. November 2011
<Click to see difference>


	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at junit.framework.TestCase.assertEquals(TestCase.java:269)
	at journal.gratitude.com.gratitudejournal.ui.util.DateUtilTest.localDateToLongString(DateUtilTest.kt:33)
```

The tests should be independent of the locale of the machine.

**Comment by alisonthemonster** [comment]
Hi there! 

You are absolutely correct! We should update these tests to use American English locale. Would you like to do this fix or shall I?
Thanks for finding this!!

**Comment by cypressious** [comment]
I'll take a stab at it.
